### ISSUE TITLE
[BUG] EnderPearl Dupe Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [XenoServers/TableSpoon#15]
**Describe the bug**
When you put a EnderPearl in a EndPortalframe and click on it, it drops so much Ender pearls

**To Reproduce**
1. Place a EndPortal Frame
2. Put EnderPearl in this frame
3. Now, click on the Endportal Frame
4. It Drops so much Pearls

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Xenophilicy** [comment]
@MonoAdrian23 This is impossible for many reasons. One being that ender pearls have no interactions with End Portal Frames whatsoever. Two being that End Portal Frames should cancel the event currently because End Portals and the End dimension are currently not implemented (nor supported) and simply don't work.

Answer these few questions and get back to me:
* What version of TableSpoon and PocketMine are you running?
* Are there any other plugins that might be conflicting? 

Try using the plugin on a server by itself (without extra plugins) and let me know if the problem persists.

**Comment by MonoAdrian23** [comment]
I use Tablespoon 0.0.5 Alpha
Pocketmine 3.14.0
Tested without any other plugins

**Comment by Xenophilicy** [comment]
Can you send me a video of it happening? I'm still not able to reproduce this on my end.
